// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYru8QaLHjjt49V8wV-o061vJ8gZ0O3BU',
    appId: '1:872245262826:web:d9b027b59df67ad339da93',
    messagingSenderId: '872245262826',
    projectId: 'jelajahin-apps',
    authDomain: 'jelajahin-apps.firebaseapp.com',
    storageBucket: 'jelajahin-apps.firebasestorage.app',
    measurementId: 'G-VS7B90S13N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY9M2B7AaWtH7Gmmh2_faV592OJ549xTk',
    appId: '1:872245262826:android:61ca7352ce71ecbf39da93',
    messagingSenderId: '872245262826',
    projectId: 'jelajahin-apps',
    storageBucket: 'jelajahin-apps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRCR6EeeYpzFCpmJIsesfILHhzcBAaIGc',
    appId: '1:872245262826:ios:44ff72beab64be5139da93',
    messagingSenderId: '872245262826',
    projectId: 'jelajahin-apps',
    storageBucket: 'jelajahin-apps.firebasestorage.app',
    iosClientId: '872245262826-fg9fc17kgutar1jsepto27mfkf0q2pec.apps.googleusercontent.com',
    iosBundleId: 'com.example.jelajahinApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRCR6EeeYpzFCpmJIsesfILHhzcBAaIGc',
    appId: '1:872245262826:ios:44ff72beab64be5139da93',
    messagingSenderId: '872245262826',
    projectId: 'jelajahin-apps',
    storageBucket: 'jelajahin-apps.firebasestorage.app',
    iosClientId: '872245262826-fg9fc17kgutar1jsepto27mfkf0q2pec.apps.googleusercontent.com',
    iosBundleId: 'com.example.jelajahinApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYru8QaLHjjt49V8wV-o061vJ8gZ0O3BU',
    appId: '1:872245262826:web:c84b0db4496bb6a839da93',
    messagingSenderId: '872245262826',
    projectId: 'jelajahin-apps',
    authDomain: 'jelajahin-apps.firebaseapp.com',
    storageBucket: 'jelajahin-apps.firebasestorage.app',
    measurementId: 'G-G5LJYRXRYC',
  );
}
